#This file is developed by Team 28 of COMP90024 of The University of Melbourne
#YING DU : 925566
#XINHUI LU : 965246
#MINCHENG LI : 889903
#MIAN WANG : 948291
#MINGZE XIA : 948737


---
- hosts: harverest
  gather_facts: no
  remote_user: ubuntu

  tasks:
  - name: Add proxy to /etc/environment
    become: true
    blockinfile:
      path: /etc/environment
      block: |
        http_proxy="http://wwwproxy.unimelb.edu.au:8000"
        https_proxy="http://wwwproxy.unimelb.edu.au:8000"
        ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"
        no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,ccc_1.novalocal,ccc_1


  - name: apt-get update
    become: true
    apt:
      force_apt_get: yes
      update_cache: yes

  # 1.1.2 install the common apt packages
  - name: install the packages using apt modules
    become: true
    apt:
      state: latest
      update_cache: yes
      name: ['python3-pip', 'git', 'vim']


  # 1.2 directory related
  # 1.2.1 mkdir the directory
  - name: mkdir the mount point
    become: true
    file:
      path: /data
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0755


  # 1.2.2 mount the volume on the directory
  - name: mkdir the mount point
    become: true
    shell: |
      mkfs.ext4 /dev/vdc
      mount /dev/vdc /data
      sleep 3
  - name: change owner of directory to ubuntu
    become: true
    command: chown -R ubuntu:ubuntu /data


  # 1.2.3 mkdir the workspace
  - name: mkdir the /data/workspace
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0777
    with_items:
      - /data/workspace



  # 1.3 clone git repo
  - name: checkout from github
    command: git clone https://github.com/MinchengL/Cluster-Cloud_Computing_Group28.git
    args:
      chdir: /data/workspace
      creates: /data/workspace/Cluster-Cloud_Computing_Group28


  # 1.4 install packages
  - name: install environemnt
    become: true
    command: pip3 install {{ item }}
    with_items:
      - couchdb
      - flask
      - virtualenv



