#This file is developed by Team 28 of COMP90024 of The University of Melbourne
#YING DU : 925566
#XINHUI LU : 965246
#MINCHENG LI : 889903
#MIAN WANG : 948291
#MINGZE XIA : 948737

---
# Install dependencies on the host
# - name: Install pip
#   become: yes
#   apt:
#     name: ['python-pip']
#     state: latest
#     update_cache: yes
#   when: ansible_distribution == "Ubuntu"
# sudo apt-get update: sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk
